---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: 
  - "Launchpad"
  - "Mail"
  - "Safari"
  - "Contacts"
  - "Notes"
  - "Reminders"
  - "Maps"
  - "Photos"
  - "Messages"
  - "FaceTime"
  - "iTunes"
  - "iBooks"
  - "TV"
  - "Podcasts"

dockitems_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1

  - name: "Firefox"
    path: "/Applications/Firefox.app"
    pos: 2

  # - name: "Visual Studio Code"
  #   path: "/Applications/Visual Studio Code.app"
  #   pos: 3

  # - name: "Slack"
  #   path: "/Applications/Slack.app"
  #   pos: 4

  # - name: "iTerm"
  #   path: "/Applications/iTerm.app"
  #   pos: 5

  # - name: "VirtualBox"
  #   path: "/Applications/Oracle VM VirtualBox.app"
  #   pos: 6

  # - name: "Spotify"
  #   path: "/Applications/Spotify.app"
  #   pos: 7

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
# dotfiles_repo_accept_hostkey: true
# dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
# dotfiles_files:
  # - .zshrc
#   - .gitignore
#   - .inputrc
#   - .osx
#   - .vimrc

homebrew_installed_packages:
  - ant
  - dockutil
  - fzf
  - gifsicle
  - git
  - git-lfs
  - gradle
  - httpie
  - imagemagick
  - maven
  - node
  - nvm
  - openssl
  - php
  - python3
  - rbenv
  - ruby-build
  - ssh-copy-id
  - wget
  - yarn
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - adoptopenjdk/openjdk

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - adoptopenjdk8
  - android-sdk
  - android-studio
  - 1password
  - chromedriver
  - firefox
  - github
  - google-chrome
  - insomnia
  - iterm2
  - sequel-ace
  - slack
  - spotify
  - vagrant
  # - virtualbox
  - visual-studio-code


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: 
  - name: "laravel/installer"
    state: present
    version: "4.2.5"

  - name: "laravel/envoy"
    state: present
    version: ""
    
  - name: "beyondcode/expose"
    state: present
    version: "2.0.2"

gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A

npm_packages:
  - name: "grunt"
    state: present
    version: "1.4.0"

pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure VSCode.
configure_vs_code: true

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

# Work on oh-my-zsh
oh_my_zsh_theme: powerlevel10k/powerlevel10k
oh_my_zsh_plugins:
  - git
  - ansible
  - zsh-autosuggestions
  - zsh-completions