---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: 
  # Our installed apps - removing them to see if it produces the same result
  - "1Password 7"
  - "Android Studio"
  - "Firefox"
  - "Github Desktop"
  - "Google Chrome"
  - "Insomnia"
  - "iTerm"
  - "Slack"
  - "Sequel Ace"
  - "Spotify"
  - "Virtualbox"
  - "Visual Studio Code"
  - "Zoom.us"
  # Preinstalled apps
  - "App Store"
  - "Contacts"
  - "FaceTime"
  - "iBooks"
  - "iTunes"
  - "Launchpad"
  - "Mail"
  - "Maps"
  - "Messages"
  - "Notes"
  - "Photos"
  - "Podcasts"
  - "Reminders"
  - "Safari"
  - "System Preferences"
  - "Terminal"
  - "TV"

dockitems_persist:
  - name: "1Password 7"
    path: "/Applications/1Password 7.app"
    pos: 1

  - name: "Android Studio"
    path: "/Applications/Android Studio.app"
    pos: 2

  - name: "Firefox"
    path: "/Applications/Firefox.app"
    pos: 3

  - name: "Github Desktop"
    path: "/Applications/Github Desktop.app"
    pos: 4

  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app"
    pos: 5

  - name: "Insomnia"
    path: "/Applications/Insomnia.app"
    pos: 6

  - name: "iTerm"
    path: "/Applications/iTerm.app"
    pos: 7

  - name: "Slack"
    path: "/Applications/Slack.app"
    pos: 8

  - name: "Sequel Ace"
    path: "/Applications/Sequel Ace.app"
    pos: 9

  - name: "Spotify"
    path: "/Applications/Spotify.app"
    pos: 10

  - name: "System Preferences"
    path: "/Applications/System Preferences.app"
    pos: 11

  - name: "VirtualBox"
    path: "/Applications/VirtualBox.app"
    pos: 12

  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app"
    pos: 13

  - name: "Zoom.us"
    path: "/Applications/Zoom.us.app"
    pos: 14

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
# dotfiles_repo_accept_hostkey: true
# dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
# dotfiles_files:
  # - .zshrc
#   - .gitignore
#   - .inputrc
#   - .osx
#   - .vimrc

homebrew_installed_packages:
  - ant
  - bat
  - composer
  - dockutil
  - fzf
  - gifsicle
  - git
  - git-lfs
  - gradle
  - httpie
  - imagemagick
  - maven
  - node
  - npm
  - nvm
  - openssl
  - php
  - python3
  - rbenv
  - ruby-build
  - ssh-copy-id
  - wget
  - yarn
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - adoptopenjdk/openjdk

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - adoptopenjdk8
  - android-sdk
  - android-studio
  - 1password
  - chromedriver
  - firefox
  - github
  - google-chrome
  - insomnia
  - iterm2
  - sequel-ace
  - slack
  - spotify
  - vagrant
  # There is an issue regarding installing virtualbox not sure why
  # - virtualbox
  - visual-studio-code
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
# Tried installing Xcode here but it didn't work with the older OS.
mas_installed_apps: []

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: 
  - name: "laravel/installer"
    state: present
    version: "4.2.5"

  - name: "laravel/envoy"
    state: present
    version: "2.7.0"

  # - name: "beyondcode/expose"
  #   state: present
  #   version: "2.0.2"

gem_packages: []

# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A

npm_packages: []

  # - name: "grunt"
  #   state: present
  #   version: "1.4.0"

pip_packages: []

  # - name: "selenium"
  #   state: present
  
  # - name: "pandas"
  #   state: present

# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure VSCode.
vs_code_configure: true
vs_code_extensions: 
  - formulahendry.auto-close-tag
  - formulahendry.auto-rename-tag
  - coenraads.bracket-pair-colorizer
  - mikestead.dotenv
  - eamodio.gitlens
  - cjhowe7.laravel-blade
  - pkief.material-icon-theme
  - equinusocio.vsc-material-theme
  - equinusocio.vsc-material-theme-icons
  - ionutvmi.path-autocomplete
  - christian-kohler.path-intellisense
  - bmewburn.vscode-intelephense-client
  - ms-python.python
  - bbenoist.vagrant
vs_code_settings: {
    "window.zoomLevel": 1,
    "workbench.iconTheme": "material-icon-theme",
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true,
    "editor.fontSize": 16,
    "workbench.colorTheme": "Sublime Material Theme - Dark",
    "terminal.integrated.fontFamily": "MesloLGS NF",
    "terminal.integrated.fontSize": 14
}


# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

# Work on oh-my-zsh
oh_my_zsh_theme: powerlevel10k/powerlevel10k
oh_my_zsh_plugins:
  - git
  - ansible
  - zsh-autosuggestions
  - zsh-completions